[package]
name = "wavs-merkler"
edition.workspace = true
version.workspace = true
authors.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
merkle-tree-rs = "0.1.0"
anyhow = { workspace = true }

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true
