[workspace]
members = [
    "app",
    "crates/bindings",
    "components/*",
]

[workspace.package]
edition = "2021"
version = "0.1.0"
license = "MIT"
authors = ["Lay3r Labs Team"]
repository = "https://github.com/Lay3rLabs/wavs"
rust-version = "1.80.0"


[workspace.dependencies]
bindings = { path = "crates/bindings" }
# must match the bindings Cargo
alloy = { git = "https://github.com/alloy-rs/alloy", rev = "v0.9.2", features = ["sol-types", "contract"] }
wit-bindgen-rt = { version = "0.32.0", features = ["bitflags"] }
