packages:
  - frontend
  - indexer

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - bufferutil
  - esbuild
  - keccak
  - secp256k1
  - sharp
  - utf-8-validate

patchedDependencies:
  '@ponder/react': patches/@ponder__react.patch
  '@react-sigma/core': patches/@react-sigma__core.patch
