package component:dao-agent;

world layer-trigger-world {
  import wavs:agent/client@0.0.1;
  import wavs:agent/config@0.0.1;
  import wavs:agent/contracts@0.0.1;
  import wavs:agent/errors@0.0.1;
  import wavs:agent/tools@0.0.1;
  import wavs:agent/types@0.0.1;

  import host: interface {
    use wavs:types/chain@0.5.1.{evm-chain-config, cosmos-chain-config};
    use wavs:worker/helpers@0.5.1.{log-level};

    get-eth-chain-config: func(chain-name: string) -> option<evm-chain-config>;
    get-cosmos-chain-config: func(chain-name: string) -> option<cosmos-chain-config>;

    log: func(level: log-level, message: string);
  }

  use wavs:worker/input@0.5.1.{trigger-action};
  use wavs:worker/output@0.5.1.{wasm-response};

  export run: func(trigger-action: trigger-action) -> result<option<wasm-response>, string>;
}
